nombre_producto = input()
CU = int(input())
PVP = int(input())
unidades_disponibles = int(input())
print("Producto: " + nombre_producto)
print("CU: " + str(CU))
print("PVP: " + str(PVP))
print("Unidades Disponibles: " + str(unidades_disponibles))
print("Ganancia: " + str((PVP - CU) * unidades_disponibles))